name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SERVER_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.DEPLOY_SERVER_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          TARGET: "/home/ubuntu/app"
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /home/ubuntu/app ; sudo docker-compose up -d --build
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          privateKey: ${{ secrets.DEPLOY_SERVER_KEY }}
